apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: hello-k8s
spec:
  title: Hello Kubernetes
  description: Introduction to Kubernetes
  vendor: Dodd Pfeffer
  difficulty: beginner
  duration: 15m
  url: https://github.com/doddatpivotal/hello-k8s-workshop
  content:
    image: jdk11-environment:*
    files: github.com/doddatpivotal/hello-k8s-workshop
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
        plugins:
          enabled: true
      docker:
        enabled: true
